### ISSUE TITLE
SIGABRT on unknown cli args

### ISSUE THREAD

**Issue by 4censord** [KoalaBear84/OpenDirectoryDownloader#117]
**Describe the bug**

On unknown command line options odd does not terminate cleanly.

**To Reproduce**
```shell
OpenDirectoryDownloader -v
```

**Expected behavior**

Help text and than a clean exit, not SIGABRT

**Screenshots**
```shell
OpenDirectoryDownloader -v
Started with PID 10804
OpenDirectoryDownloader 2.3.0.3
Copyright (C) 2022 OpenDirectoryDownloader

ERROR(S):
  Option 'v' is unknown.

[Help text]

Error command line parameter 'UnknownOptionError'
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at OpenDirectoryDownloader.Program.Main(String[] args) in /home/runner/work/OpenDirectoryDownloader/OpenDirectoryDownloader/src/OpenDirectoryDownloader/Program.cs:line 77
   at OpenDirectoryDownloader.Program.<Main>(String[] args)
fish: Job 1, 'OpenDirectoryDownloader -v' terminated by signal SIGABRT (Abort)
```
**Desktop:**

- OS: Linux 5.18.5-arch1-1
- Version: 2.3.1.0

**Comment by KoalaBear84** [comment]
Hmm, GitHub is lagging behind in mails, received a mail about this an hour ago, but the ticket is already 5 hours old.

**Comment by KoalaBear84** [comment]
https://github.com/KoalaBear84/OpenDirectoryDownloader/releases/tag/v2.3.1.2

**Comment by 4censord** [comment]
This seems to have fixed it.
