### ISSUE TITLE
Protocal unsuported even though I have enabled TLS 1.3

### ISSUE THREAD

**Issue by inyourface34456** [KoalaBear84/OpenDirectoryDownloader#140]
**Describe the bug**
I Tried to index [https://isidore.co/CalibreLibrary/](https://isidore.co/CalibreLibrary/)

**To Reproduce**
1. Open Application
2. press enter
3. wait

**Expected behavior**
The program will function normally.

**Screenshots**
![The Program)](https://github.com/user-attachments/assets/6849e8e0-c7e0-457c-acfd-bd3eec5f6457)
I have enabled TLS 1.3, witch is why I am posting this here.  What is the issue?

**Desktop (please complete the following information):**
 - Window 10
 - Latest Stable

**Comment by KoalaBear84** [comment]
Hmm.. I'm having the same issue with another site. And I couldn't figure it out in a short that when I checked.

It looks like for both sites where the issue is that at least TLS 1.2 is not available, and it might indeed go to TLS 1.3.

https://www.cdn77.com/tls-test/result?domain=isidore.co
https://www.cdn77.com/tls-test/result?domain=hoj-clan.fr

I need to look into it further. Probably will not be this week because of a (work) exam.

It could be that TLS 1.0 and 1.1 are disabled on Windows, which might be 'good', and that TLS 1.3 isn't fully working. Maybe only in .NET, I'm not sure yet.

**Comment by KoalaBear84** [comment]
Still no idea why it fails and how it can be solved. Had another one.

https://logiciels.ycharbi.fr/

**Comment by KoalaBear84** [comment]
I have it with another site. And I have it enabled in Windows 10. But it looks like it is still an issue. This time I'm getting this error:

```
System.Net.Http.HttpRequestException
  HResult=0x80131620
  Message=The SSL connection could not be established, see inner exception.
  Source=System.Net.Http
  StackTrace:
   at System.Net.Http.ConnectHelper.<EstablishSslConnectionAsync>d__2.MoveNext()
   at System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter.GetResult()
   at System.Net.Http.HttpConnectionPool.<ConnectAsync>d__53.MoveNext()
   at System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter.GetResult()
   at System.Net.Http.HttpConnectionPool.<CreateHttp11ConnectionAsync>d__81.MoveNext()
   at System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter.GetResult()
   at System.Net.Http.HttpConnectionPool.<InjectNewHttp11ConnectionAsync>d__80.MoveNext()
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.<WaitWithCancellationAsync>d__1.MoveNext()
   at System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter.GetResult()
   at System.Net.Http.HttpConnectionWaiter`1.<WaitForConnectionWithTelemetryAsync>d__6.MoveNext()
   at System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter.GetResult()
   at System.Net.Http.HttpConnectionPool.<SendWithVersionDetectionAndRetryAsync>d__52.MoveNext()
   at System.Net.Http.DiagnosticsHandler.<SendAsyncCore>d__10.MoveNext()
   at System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter.GetResult()
   at System.Net.Http.RedirectHandler.<SendAsync>d__4.MoveNext()
   at System.Net.Http.SocketsHttpHandler.<<SendAsync>g__CreateHandlerAndSendAsync|115_0>d.MoveNext()
   at System.Net.Http.HttpClient.<<SendAsync>g__Core|83_0>d.MoveNext()

Inner Exception 1:
IOException: Received an unexpected EOF or 0 bytes from the transport stream.
```

I guess it only happens on Windows 10 and a site that does not have TLS 1.2 enabled. 

https://www.ipvoid.com/tls-checker/

I just cannot get it to work, I'm still on Windows 10 myself for as long as possible until the Windows 11 taskbar is fixed.

**Comment by KoalaBear84** [comment]
OK, lately checked it again, it's just not possible on Windows 10.. And looks like more and more sites abandoned TLS 1.2. The sites do work in the browser, but not in the .NET HttpClient. 🤯🐵
