### ISSUE TITLE
Unable to save URL list to file

### ISSUE THREAD

**Issue by infosecconsultant** [KoalaBear84/OpenDirectoryDownloader#18]
Hi, 

The application is currently crashing regularly when attempting to run the following commands 

```
PS G:\> .\OpenDirectoryDownloader.exe -u http://31.22.89.2/cisco/ -j
```

```
Started
URL specified: http://31.22.89.2/cisco/
URL fixed: http://31.22.89.2/cisco/
Started indexing!
****************************************************************************
****************************************************************************
***  Press I for info (this)                                             ***
***  Press S for statistics                                              ***
***  Press T for thread info                                             ***
***  Press J for Save JSON                                               ***
***                                                                      ***
***  Press ESC to EXIT                                                   ***
****************************************************************************
****************************************************************************
2019-11-28 16:13:05.0349  [9]  WARN OpenDirectoryIndexer.TimerStatistics_Elapsed Http status codes
200: 90
Total files: 4,532, Total estimated size: 100.3 GiB
Total directories: 90
Total HTTP requests: 95, Total HTTP traffic: 1.45 MiB
|**Url:** http://31.22.89.2/cisco/|||
|:-|-:|-:|
|**Date:** 11/28/2019 5:12:35 AM +00:00|**Time:** 00:00:30||

2019-11-28 16:13:05.0448  [9]  WARN OpenDirectoryIndexer.TimerStatistics_Elapsed Queue: 78, Queue (filesizes): 0
2019-11-28 16:13:35.0240 [11]  WARN OpenDirectoryIndexer.TimerStatistics_Elapsed Http status codes
200: 180
Total files: 6,423, Total estimated size: 143.06 GiB
Total directories: 180
Total HTTP requests: 184, Total HTTP traffic: 2.36 MiB
|**Url:** http://31.22.89.2/cisco/|||
|:-|-:|-:|
|**Date:** 11/28/2019 5:12:35 AM +00:00|**Time:** 00:01:00||

2019-11-28 16:13:35.0404 [11]  WARN OpenDirectoryIndexer.TimerStatistics_Elapsed Queue: 0, Queue (filesizes): 0
2019-11-28 16:13:35.7381 [28] ERROR DirectoryParser.CheckSymlinks Possible virtual directory or symlink detected (level 1)! SKIPPING! Url: http://31.22.89.2/cisco/www.mmnt.net/db/0/
Finshed indexing
Saving URL list to file...
```
Then the following error occurs:
```
2019-11-28 16:13:35.9167 [18] ERROR <<StartIndexingAsync>b__0>d.MoveNext System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\admin\AppData\Local\Temp\.net\OpenDirectoryDownloader\bygfrh2s.ae1\Scans\http___31.22.89.2_cisco_.txt'.
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.StreamWriter.ValidateArgsAndOpenPath(String path, Boolean append, Encoding encoding, Int32 bufferSize)
   at System.IO.StreamWriter..ctor(String path)
   at System.IO.File.WriteAllText(String path, String contents)
   at OpenDirectoryDownloader.OpenDirectoryIndexer.<>c__DisplayClass50_0.<<StartIndexingAsync>b__0>d.MoveNext() System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\admin\AppData\Local\Temp\.net\OpenDirectoryDownloader\bygfrh2s.ae1\Scans\http___31.22.89.2_cisco_.txt'.
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.StreamWriter.ValidateArgsAndOpenPath(String path, Boolean append, Encoding encoding, Int32 bufferSize)
   at System.IO.StreamWriter..ctor(String path)
   at System.IO.File.WriteAllText(String path, String contents)
   at OpenDirectoryDownloader.OpenDirectoryIndexer.<>c__DisplayClass50_0.<<StartIndexingAsync>b__0>d.MoveNext()
```
And the application contiues.
```
Starting speedtest (10-25 seconds)...
Test file: 421.8 MiB http://31.22.89.2/cisco/120xxXR/XR12000-iosxr-k9-4.0.0.tar

```

No list of URL's is generated. 

I am using the OpenDirectoryDownloader-1.2.0.0.zip version from the releases section on windows 10. Running from an external HDD and via PowerShell. 

I did notice that when I run 

``` 
PS G:\> .\OpenDirectoryDownloader.exe --help
```
I get the following output (and subsequent crash)
```
Started
OpenDirectoryDownloader 1.0.0
Copyright (C) 2019 OpenDirectoryDownloader

  -u, --url                 Url to scan

  -t, --threads             (Default: 5) Number of threads

  -q, --quit                (Default: false) Do not wait after scanning

  -j, --json                (Default: false) Save JSON file

  -f, --no-urls             (Default: false) Do not save URLs file

  -r, --no-reddit           (Default: false) Do not show Reddit stats markdown

  -e, --exact-file-sizes    (Default: false) Exact file sizes (WARNING: Uses HEAD requests which takes more time and is heavier for server)

  -l, --upload-urls         (Default: false) Uploads urls file

  -s, --speed-test          (Default: false) Do a speed test

  --help                    Display this help screen.

  --version                 Display version information.

Error command line parameter 'HelpRequestedError'

Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at OpenDirectoryDownloader.Program.Main(String[] args)
   at OpenDirectoryDownloader.Program.<Main>(String[] args)
PS G:\>
```

Not sure what else I can tell you really. Any advice would be appreciated. 

Cheers

**Comment by KoalaBear84** [comment]
Aww. I really need to fix the builds. This is because this is the single file solution.

Could you try the first build (as a workaround).

I need to get the GitHub Actions to zip the build and publish it as a Release in GitHub.

**Comment by KoalaBear84** [comment]
Newest release and. I'll close it as I don't get any response.

https://github.com/KoalaBear84/OpenDirectoryDownloader/releases/tag/v1.4.0.0
