### ISSUE TITLE
Document xclip requirement

### ISSUE THREAD

**Issue by MCOfficer** [KoalaBear84/OpenDirectoryDownloader#38]
**Describe the bug**
Trying to copy to the clipboard on linux without having xclip installed results in an error:
```
Press ESC to exit! Or C to copy to clipboard and quit!
2020-10-07 11:33:44.9066  [1] ERROR Command.ProcessConsoleInput Error processing action System.Exception: Could not execute process. Command line: bash -c "cat /tmp/tmpW9nSm7.tmp | xclip -i -selection clipboard".
Output: 

Error: bash: xclip: command not found


   at BashRunner.Run(String commandLine) in C:\projects\textcopy\src\TextCopy\BashRunner.cs:line 45
   at LinuxClipboard.SetText(String text) in C:\projects\textcopy\src\TextCopy\LinuxClipboard_2.1.cs:line 33
   at TextCopy.ClipboardService.SetText(String text) in C:\projects\textcopy\src\TextCopy\ClipboardService.cs:line 65
   at OpenDirectoryDownloader.Command.ProcessConsoleInput(OpenDirectoryIndexer openDirectoryIndexer) in D:\a\OpenDirectoryDownloader\OpenDirectoryDownloader\OpenDirectoryDownloader\Command.cs:line 115
Unhandled exception. System.Exception: Could not execute process. Command line: bash -c "cat /tmp/tmpW9nSm7.tmp | xclip -i -selection clipboard".
Output: 

Error: bash: xclip: command not found


   at BashRunner.Run(String commandLine) in C:\projects\textcopy\src\TextCopy\BashRunner.cs:line 45
   at LinuxClipboard.SetText(String text) in C:\projects\textcopy\src\TextCopy\LinuxClipboard_2.1.cs:line 33
   at TextCopy.ClipboardService.SetText(String text) in C:\projects\textcopy\src\TextCopy\ClipboardService.cs:line 65
   at OpenDirectoryDownloader.Command.ProcessConsoleInput(OpenDirectoryIndexer openDirectoryIndexer) in D:\a\OpenDirectoryDownloader\OpenDirectoryDownloader\OpenDirectoryDownloader\Command.cs:line 115
   at OpenDirectoryDownloader.Program.Main(String[] args) in D:\a\OpenDirectoryDownloader\OpenDirectoryDownloader\OpenDirectoryDownloader\Program.cs:line 97
   at OpenDirectoryDownloader.Program.<Main>(String[] args)

```

This is probably unavoidable, but should be documented in the READMEE.

**To Reproduce**
1. Set up a *nix computer without xclip
2. Run a scan
3. When prompted, press `C` to copy

**Comment by KoalaBear84** [comment]
I see it at https://github.com/CopyText/TextCopy

![image](https://user-images.githubusercontent.com/5886900/95326221-8724eb80-08a2-11eb-94b1-57ce388536e3.png)

Have no clue about what to do with this. I might check if they can implement a availability check for it which I can call before.

Does OpenDirectoryDownloader crashes with it?

**Comment by KoalaBear84** [comment]
I've added a question-like issue on it to ask what is the best way to handle it.

https://github.com/CopyText/TextCopy/issues/291

**Comment by KoalaBear84** [comment]
Added release with error handling for now. Will still not copy, but shows the error without crashing. Not that it makes much difference, because the following line will stop the application. But at least it's handled.

https://github.com/KoalaBear84/OpenDirectoryDownloader/releases/tag/v1.6.0.3

**Comment by KoalaBear84** [comment]
The issue on xclip is closed. If somebody will supply a PR on xclip it could be 'solved', but xclip should always be installed for it to work. Closing as there is nothing more we can do.

**Comment by MCOfficer** [comment]
It could be listed as [Prerequisite](https://github.com/KoalaBear84/OpenDirectoryDownloader#prerequisites).

**Comment by KoalaBear84** [comment]
That's a good suggestion indeed, added with https://github.com/KoalaBear84/OpenDirectoryDownloader/commit/c2fce6992ddf9509a63be413b2f48b070a296b9a
