### ISSUE TITLE
Speedtest not possible when spawing the process

### ISSUE THREAD

**Issue by Chaphasilor** [KoalaBear84/OpenDirectoryDownloader#49]
**Describe the bug**

When I spawn ODD in Node.js and add the `--speedtest`-flag, the speedtest fails with an error about an invalid handle

**To Reproduce**
1. Spawn ODD in Node.js with the speedtest argument:  
    ```js
    const oddProcess = spawn(<string with path to executable>, [`-u ${url}`, `--quit`, `--speedtest`]);
      
    oddProcess.stdout.on('data', (data) => {
      console.log(`stdout: ${data}`);
    });
      
    oddProcess.stderr.on('data', (data) => {
      console.error(`stderr: ${data}`);
    });
    ```
2. Look at the output. It should say something like the following:  
    ```shell
    Starting speedtest (10-25 seconds)...
    Test file: 21 GiB
    http://178.32.222.201/%5bAniDub%5d_Kara_no_Kyoukai_%5bBDRip1080p_h264_Flac%5d%5bSuzaku%5d/%5bAniDub%5d_Kara_no_Kyoukai_%5bMovie_5%5d_Paradox_Paradigm_%5bBDRip1080p_h264_Aac%5d%5bSuzaku%5d.mkv
    2020-11-29 21:17:07.2102 [15] ERROR OpenDirectoryIndexer.StartIndexingAsync Speedtest failed System.IO.IOException: The handle is invalid.
       at System.ConsolePal.GetBufferInfo(Boolean throwOnNoConsole, Boolean& succeeded)
       at System.ConsolePal.GetBufferInfo()
       at System.ConsolePal.GetCursorPosition()
       at OpenDirectoryDownloader.Library.ClearCurrentLine()
       at OpenDirectoryDownloader.Library.SpeedtestFromStream(Stream stream, Int32 seconds)
       at OpenDirectoryDownloader.Library.DoSpeedTestHttpAsync(HttpClient httpClient, String url, Int32 seconds)
       at OpenDirectoryDownloader.OpenDirectoryIndexer.<>c__DisplayClass51_0.<<StartIndexingAsync>b__0>d.MoveNext()
    ```

**Expected behavior**
The speedtest should work (and does work when using ODD in cli mode.

**Desktop (please complete the following information):**
 - OS: Windows 10 (64 bit)
 - Runtime: Node.js v14.15.1
 - Client: OpenDirectoryDownloader v1.9.0.9

**Comment by KoalaBear84** [comment]
Hmm... I do know that it is tricky to get it right in all situations. Looks like nobody on the internet has got this "Node.js System.ConsolePal.GetBufferInfo".. 😮

Changed the script a bit to make it work (for me).

```javascript
const cp = require('child_process');
const url = `http://91.190.42.70:8889/`;
const oddProcess = cp.spawn(`C:/Repositories/OpenDirectoryDownloader/OpenDirectoryDownloader/bin/x64/Debug/net5.0/OpenDirectoryDownloader.exe`, [`-u ${url}`, `--quit`, `--speedtest`]);
  
oddProcess.stdout.on('data', (data) => {
  console.log(`stdout: ${data}`);
});
  
oddProcess.stderr.on('data', (data) => {
  console.error(`stderr: ${data}`);
});
```

Now see if there is a way to fix it 🤔

**Comment by KoalaBear84** [comment]
Hmm, can also reproduce this just in another process where the console is 'redirected'. Already checking it for some other things, might just skip intermediate download speed results.

**Comment by KoalaBear84** [comment]
Build running.

**Comment by KoalaBear84** [comment]
Check https://github.com/KoalaBear84/OpenDirectoryDownloader/releases/tag/v1.9.1.0

**Comment by Chaphasilor** [comment]
Working, thanks :D

**Comment by KoalaBear84** [comment]
Great 👍
