### ISSUE TITLE
Fix HelpRequestedError and VersionRequestedError

### ISSUE THREAD

**Issue by KoalaBear84** [KoalaBear84/OpenDirectoryDownloader#54]
**Describe the bug**
Based on errors in and while running to fix #50

`OpenDirectoryDownloader.exe --help`

```
Error command line parameter 'HelpRequestedError'
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at OpenDirectoryDownloader.Program.Main(String[] args)
   at OpenDirectoryDownloader.Program.<Main>(String[] args)
```

`OpenDirectoryDownloader.exe --version`

```
Error command line parameter 'VersionRequestedError'
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at OpenDirectoryDownloader.Program.Main(String[] args)
   at OpenDirectoryDownloader.Program.<Main>(String[] args)
```

**Expected behavior**
No errors

**Desktop (please complete the following information):**
 - OS: win-x64
 - Version 1.9.1.2

**Comment by Chaphasilor** [comment]
Sorry, but my C#-fu isn't good enough to fix this 😅
