### ISSUE TITLE
401 Forbidden error despite specifying username & password

### ISSUE THREAD

**Issue by chinmay241** [KoalaBear84/OpenDirectoryDownloader#92]
I am trying to get the directory links/listing of a workers.dev Website. There is HTTPD Username/Password authentication.

Generally on the browser I would login by entering this into the URL: https://@xxx:@xxx@archive.xxx.workers.dev
So I tried similar approach and i get this error:

```
>OpenDirectoryDownloader.exe --url "https://@xxx:@xxx@archive.xxx.workers.dev"
Started with PID 2004
URL specified: https://@xxx:@xxx@archive.xxx.workers.dev
Unhandled exception. System.UriFormatException: Invalid URI: Invalid port specified.
   at System.Uri.CreateThis(String , Boolean , UriKind ) in System.Private.Uri.dll:token 0x6000082+0x69
   at System.Uri..ctor(String uriString) in System.Private.Uri.dll:token 0x600003b+0x14
   at OpenDirectoryDownloader.Library.FixUrl(String url) in D:\a\OpenDirectoryDownloader\OpenDirectoryDownloader\src\OpenDirectoryDownloader\Library.cs:line 88
   at OpenDirectoryDownloader.Program.Main(String[] args) in D:\a\OpenDirectoryDownloader\OpenDirectoryDownloader\src\OpenDirectoryDownloader\Program.cs:line 100
   at OpenDirectoryDownloader.Program.<Main>(String[] args) in OpenDirectoryDownloader.dll:token 0x60000ad+0xc
```

If I specify a Username and Password in their fields it fails as well.

```
>OpenDirectoryDownloader.exe --url "https://archive.xxx.workers.dev" --username @xxx --password @xxx
Started with PID 20816
URL specified: https://archive.xxx.workers.dev
URL fixed    : https://archive.xxx.workers.dev/
Started indexing!
┌─────────────────────────────────────────────────────────────────────────┐
│ KoalaBear84/OpenDirectoryDownloader 2.0.0.0                             │
├─────────────────────────────────────────────────────────────────────────┤
│ Press I for info (this)                                                 │
│ Press S for statistics                                                  │
│ Press T for thread info                                                 │
│ Press U for Save TXT                                                    │
│ Press J for Save JSON                                                   │
├─────────────────────────────────────────────────────────────────────────┤
│ Press ESC or X to EXIT                                                  │
└─────────────────────────────────────────────────────────────────────────┘

2021-06-26 17:01:24.5383 [11]  WARN OpenDirectoryIndexer.ProcessWebDirectoryAsync First request fails, using Curl fallback User-Agent
2021-06-26 17:01:24.5931 [11]  WARN OpenDirectoryIndexer.ProcessWebDirectoryAsync First request fails, using Chrome fallback User-Agent
2021-06-26 17:01:24.6918 [11]  WARN OpenDirectoryIndexer..ctor [P1] Error Response status code does not indicate success: 401 (Unauthorized). retrieving on try 1 for url '/'. Waiting 2 seconds.
2021-06-26 17:01:26.9352 [11]  WARN OpenDirectoryIndexer.ProcessWebDirectoryAsync First request fails, using Curl fallback User-Agent
2021-06-26 17:01:26.9949 [11]  WARN OpenDirectoryIndexer.ProcessWebDirectoryAsync First request fails, using Chrome fallback User-Agent
2021-06-26 17:01:27.0588 [11]  WARN OpenDirectoryIndexer..ctor [P1] Error Response status code does not indicate success: 401 (Unauthorized). retrieving on try 2 for url '/'. Waiting 4 seconds.
2021-06-26 17:01:31.2852 [11]  WARN OpenDirectoryIndexer.ProcessWebDirectoryAsync First request fails, using Curl fallback User-Agent
2021-06-26 17:01:31.3474 [11]  WARN OpenDirectoryIndexer.ProcessWebDirectoryAsync First request fails, using Chrome fallback User-Agent
2021-06-26 17:01:31.4032 [11]  WARN OpenDirectoryIndexer..ctor [P1] Error Response status code does not indicate success: 401 (Unauthorized). retrieving on try 3 for url '/'. Skipping..
2021-06-26 17:01:31.4032 [11] ERROR OpenDirectoryIndexer.WebDirectoryProcessor Skipped processing Url: 'https://archive.xxx.workers.dev/'
Finshed indexing
|**Url:** https://archive.xxx.workers.dev/|||
|:-|-:|-:|
|**Extension (Top 5)**|**Files**|**Size**|
|**Dirs:** 1 **Ext:** 0|**Total:** 0|**Total:** n/a|
|**Date (UTC):** 2021-06-26 15:01:23|**Time:** 00:00:09||

^(Created by [KoalaBear84's OpenDirectory Indexer](https://github.com/KoalaBear84/OpenDirectoryDownloader/))

No URLs to save
Http status codes
401: 3
Total files: 0, Total estimated size: n/a
Total directories: 1
Total HTTP requests: 1, Total HTTP traffic:  B
|**Url:** https://archive.xxx.workers.dev/|||
|:-|-:|-:|
|**Extension (Top 5)**|**Files**|**Size**|
|**Dirs:** 1 **Ext:** 0|**Total:** 0|**Total:** n/a|
|**Date (UTC):** 2021-06-26 15:01:23|**Time:** 00:00:09||

^(Created by [KoalaBear84's OpenDirectory Indexer](https://github.com/KoalaBear84/OpenDirectoryDownloader/))

URLs with errors:
https://archive.xxx.workers.dev/
Finished indexing!
Press ESC to exit! Or C to copy to clipboard and quit!
```

Any help appreciated. Thank you!

**Comment by Chaphasilor** [comment]
Try putting quotes (`"`) around both the username and the password when passing the flags.

If that doesn't work, try opening a new incognito windows and navigating to the OD, the browser should prompt you for username and password.  
If that doesn't happen, HTTP Basic probably isn't used...

**Comment by Chaphasilor** [comment]
@chinmay241 is this still a problem? have you tried my "solution"? :)

**Comment by KoalaBear84** [comment]
Closing because of no response
